# Generated by Django 3.2.9 on 2021-11-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='on_sale_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
